### ISSUE TITLE
jwks-rsa publishes examples to npm registry which causes security violations

### ISSUE THREAD

**Issue by anthony-telljohann** [auth0/node-jwks-rsa#189]
### Description

> `jwks-rsa` publishes the `examples` directory to npm. The examples contain non-production code which security tools such as NexusIQ will scan and report vulnerabilities on which is the case with `koa`.

**Comment by richgerrard** [comment]
We also consume you, and we are seeing `CVE-2020-15084` flagged in our CI process because you are including `express-jwt` in your example directory:
Ex: /usr/src/app/node_modules/jwks-rsa/examples/express-demo/node_modules/express-jwt

It is imperative that you do not include dependencies in the example folder of your node module.
