### ISSUE TITLE
Upgrade the jose version to >= 3.11.4

### ISSUE THREAD

**Issue by sklakken** [auth0/node-jwks-rsa#262]
At my company we use the Aqua Security Scanner that is failing my build because the jwks_rsa library depends on an older version of jose (2.0.2).  The jose vulnerabilities can be found at the following links.

https://nvd.nist.gov/vuln/detail/CVE-2021-29446
https://nvd.nist.gov/vuln/detail/CVE-2021-29445
https://nvd.nist.gov/vuln/detail/CVE-2021-29444

The ideal solution would be to simply update jwks-rsa to use jose version 3.11.4 or better.

Thank you!

**Comment by panva** [comment]
You are free to ignore that report, Aqua Security is not reporting this correctly.

- neither one of those CVEs is actually for the `jose` npm module
- the `jose` npm module vulnerability was fixed in ^2.0.5. See https://github.com/panva/jose/security/advisories/GHSA-58f5-hfqc-jgch
- the vulnerability itself is not related to a feature `jwks-rsa` uses
