### ISSUE TITLE
passport typescript type conflict

### ISSUE THREAD

**Issue by wyattjoh** [auth0/node-jwks-rsa#47]
Trying to use this package along with a custom passport strategy with express.

Issue is that this package includes the definitions from express-jwt, which are causing issues with projects that include both passport and node-jwks-rsa.

https://github.com/DefinitelyTyped/DefinitelyTyped/issues/23976

Any recommendations to resolve this conflict of the `Request.user` type?

```text
node_modules/@types/express-jwt/index.d.ts(43,13): error TS2717: Subsequent property declarations must have the same type.  Property 'user' must be of type 'User | undefined', but here has type 'any'.
```

**Comment by joshcanhelp** [comment]
@wyattjoh - Thanks for the report here! We're taking a look internally and post back when we have a path forward :+1:

**Comment by joshcanhelp** [comment]
@wyattjoh - I wanted to check back in with you here ... it looks like the main culprit here is a change made to the Passport definitions earlier this year ([commit](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/c75ee379eb78e44d3c7a04d0ab4f10ed93625c1d)). That switched it from `any` to `User`, which collides with the `any` directive in Express JWT. I'm going to put through a PR to DefinitelyTyped to hopefully correct this but would like to be able to test it out first before doing that. 

Can you provide some simple repro steps to generate this error? If your project is open source and has install instructions, that would be fine. Otherwise, just a way that I can generate that error, then test with the fix in place. 

Thank you!

**Comment by wyattjoh** [comment]
Sure @joshcanhelp!

You can grab the following repo/branch: https://github.com/coralproject/talk/pull/1743

```bash
git clone https://github.com/coralproject/talk.git
cd talk
git checkout next-passport
npm install
npm run compile:graphql
npm run build:server
```

That currently, will throw the following error:

```
node_modules/@types/express-jwt/index.d.ts(43,13): error TS2717: Subsequent property declarations must have the same type.  Property 'user' must be of type 'User | undefined', but here has type 'any'.
```

**Comment by joshcanhelp** [comment]
Thanks for that, works as expected ... AFAIK :)

And just so I'm sure, I'm expecting no errors and a `/dist/` folder created with compiled JS? If so, that's what I get with my proposed fix for this:

```ts
// node_modules/@types/passport/index.d.ts:15

declare global {
    namespace Express {
        interface Request {
            authInfo?: any;
            user?: User | any; // still use the `User` interface but allow `any` as well
            // ...
        }
    }
}
```

If you can just confirm what I'm getting or make that change and try it out, I'll put through a PR for that.

**Comment by wyattjoh** [comment]
That looks like it works perfectly @joshcanhelp! Would love a PR submitted to resolve it 😄

**Comment by joshcanhelp** [comment]
PR submitted: DefinitelyTyped/DefinitelyTyped/#27339
