### ISSUE TITLE
Promise Methods

### ISSUE THREAD

**Issue by shellscape** [auth0/node-jwks-rsa#76]
Not to be curt, but it's 2019 folks. Callbacks are relics and `Promise` is the way forward. The last version of Node that doesn't support async/await out of the box is on its last leg and will soon drop out of LTS. Can we _please_ get an updated version that doesn't solely rely on callbacks?

**Comment by shellscape** [comment]
@joshcanhelp aggressive bot is overly aggressive. please don't dismiss my issue and the 18 upvotes this issue received.

**Comment by cocojoe** [comment]
Agreed, sorry about that. The bot appears to be a little over zealous in its desire to close issues.

**Comment by shellscape** [comment]
Thank you for the re-open.

**Comment by dmi3y** [comment]
There is https://github.com/aneilbaboo/node-jwks-rsa-promisified

**Comment by the-architect** [comment]
Just found out about this, so maybe someone else can use it too.

You can promisify callback methods like this:

```javascript
const { promisify } = require("util");
const jwksClient = require("jwks-rsa");

...

const client = jwksClient({ <yourOptions> });

// promisify the function:
const getSigningKey = promisify(client.getSigningKey);

// use it like any other promise:
const key = await getSigningKey(kid);
```

**Comment by vinerich** [comment]
I know this is a node library but I'd also like to be able to use this on frontend sites to verify tokens.

The next part can be wrong, only starting with js in browsers so correct me here:
- Through the callbacks `setImmediate()` is used, which is supported by node but not by browsers.
- This is not supported in any browser except Microsofts IE/Edge [https://caniuse.com/#feat=setimmediate](https://caniuse.com/#feat=setimmediate).

So please don't just promisify the existing callbacks, since this will not change the call to `setImmediate()`.

**Comment by ken5scal** [comment]
I'm experiencing the same behavior in spa as @vinerich described.
