### ISSUE TITLE
Basic usage doesn't work in TypeScript

### ISSUE THREAD

**Issue by samuela** [auth0/node-jwks-rsa#78]
The following code works according to the example code, and runs just fine but does not compile:
```typescript
import * as jwksRsa from "jwks-rsa";

export function makeJwksClient(auth0Domain: string) {
  return jwksRsa({
    cache: true,
    jwksUri: `${auth0Domain}/.well-known/jwks.json`,
  });
}
```

TypeScript complains:
```
$ tsc --noEmit
../common/index.ts:5:10 - error TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof JwksRsa' has no compatible call signatures.

5   return jwksRsa({
           ~~~~~~~~~
6     cache: true,
  ~~~~~~~~~~~~~~~~
7     jwksUri: `${auth0Domain}/.well-known/jwks.json`,
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
8   });
  ~~~~

  ../common/index.ts:2:1
    2 import * as jwksRsa from "jwks-rsa";
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Type originates at this import. A namespace-style import cannot be called or constructed, and will cause a failure at runtime. Consider using a default import or import require here instead.


Found 1 error.
```

**Comment by samuela** [comment]
bump

**Comment by llienard** [comment]
Try to import jwks-rsa as default : `import jwksRsa from "jwks-rsa";`

**Comment by leaumar** [comment]
> Try to import jwks-rsa as default : import jwksRsa from "jwks-rsa";

I can confirm this works with `tsc test.ts --esModuleInterop`:
```typescript
import jwksRsa from "jwks-rsa";
console.info(jwksRsa({jwksUri: ""}));
```

But it would be nice if it worked normally.

The following fails despite compiling:
```typescript
import {JwksClient} from "jwks-rsa";
console.info(new JwksClient({jwksUri: ""}));
```
This works but violates common linting rules and has high wtf/min in code reviews: 😁 
```typescript
import * as jwks from "jwks-rsa";
import {ClientOptions, JwksClient} from "jwks-rsa";
const createClient = (jwks as unknown) as (options: ClientOptions) => JwksClient;
console.info(createClient({jwksUri: ""}));
```

I think the problem is this in your index.d.ts:
```typescript
declare function JwksRsa(options: JwksRsa.ClientOptions): JwksRsa.JwksClient;
declare namespace JwksRsa { 
  class JwksClient {
    constructor(options: ClientOptions);
  }
}
export = JwksRsa;
```
Having a duplicate identifier seems strange, and the class with constructor probably doesn't match reality since calling the constructor throws a `TypeError` that it isn't a constructor.

**Comment by nicolaracco** [comment]
Using esModuleInterop cannot be considered a solution because it creates incompatibilities with other libraries. I've used the workaround proposed by @leaumar but, as they say, it has high wtf/min reaction.

**Comment by adamjmcgrath** [comment]
Hi @llienard @leaumar @nicolaracco 

This library [exports commonjs](https://github.com/auth0/node-jwks-rsa/blob/master/src/index.js#L9). In order to model this in typescript we've used `export =`.

When exporting a module using `export =`, TypeScript-specific `import module = require("module")` should be used to import the module (see: https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require). So the following would work:

```typescript
import jwksRsa = require("jwks-rsa");
console.info(jwksRsa({jwksUri: ""}));
```

If you want to have this common js library interoperate with es modules (eg you want to use it with a default import) - then you'll need to use the `esModuleInterop` flag.

> Having a duplicate identifier seems strange

This is expected, have a look at the function with extra fields example in https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-d-ts.html

**Comment by leaumar** [comment]
@adamjmcgrath 
Using `require` violates my project's rules:

> TS1202: Import assignment cannot be used when targeting ECMAScript modules. Consider using 'import * as ns from "mod"', 'import {a} from "mod"', 'import d from "mod"', or another module format instead.
> ESLint: A `require()` style import is forbidden.(@typescript-eslint/no-require-imports)

Is there no change/addition you could make to the library that would be fully backward compatible (obviously) but also allow it to work hassle-free (including no compatibility settings like `esModuleInterop`) in the type of projects it currently doesn't work in? This is the only library I have this issue with. I'm not in a position to offer the solution myself because I'm not a pro on the whole module ecosystem and compatibility tricks.

**Comment by nicolaracco** [comment]
@adamjmcgrath Using `esModuleInterop` is not standard nor recommended in typescript. Using it creates problems with other libraries (in my case I was already trying with `esModuleInterop` and got errors when using sharp if I recall correctly).

**Comment by adamjmcgrath** [comment]
This library is not an ES module, it's a CJS module, so if you want to use it like an ES Module with a default import `import jwksRsa from "jwks-rsa";` - you need to use `esModuleInterop`

> @adamjmcgrath Using esModuleInterop is not standard nor recommended in typescript. 

I'm not aware of any recommendation from typescript against the use of `esModuleInterop` or any TypeScript standards that don't include it, but I'd be happy to take a look at any.

If you don't want to use `esModuleInterop` you can try:

```js
import * as jwks from "jwks-rsa";
console.log(jwks({jwksUri: ""}));
```

> This is the only library I have this issue with.

@leaumar - are you able to share your project? Do you use express, hapi or koa? They're CJS modules and I'd be interested to know how you import them

**Comment by leaumar** [comment]
I checked the work project that made me reply on this thread, someone has enabled moduleInterop there in the meantime to stop having these problems (with koa and hapi indeed).

In some private projects, where I want stricter rules, I got around the issue by... finding alternative libraries for the few that gave me this.

I don't think there's really a question about what the technical issue is anymore, it's more about what can be done to improve UX (i.e. make jwks-rsa all-compatible):
> Is there no change/addition you could make to the library that would be fully backward compatible (obviously) but also allow it to work hassle-free (including no compatibility settings like esModuleInterop) in the type of projects it currently doesn't work in?

^ honest question

**Comment by adamjmcgrath** [comment]
> import * as jwks from "jwks-rsa"; requires enabling allowSyntheticDefaultImports if I'm not mistaken. It's not as bad as moduleInterop, but still configuration creep.

This works for me with zero config, see https://repl.it/@AdamMcGrath/ProbableHomelyMonitor

> I don't think there's really a question about what the technical issue is anymore, it's more about what can be done to improve UX (i.e. make jwks-rsa all-compatible)

We do the same as express (and probably koa, hapi, etc..). I don't think we can do more than that (without converting the library itself to es modules)

## jwks-rsa

```typescript
declare function JwksRsa(options: JwksRsa.ClientOptions): JwksRsa.JwksClient;

declare namespace JwksRsa {
  class JwksClient {
    ...
  }

...
}

export = JwksRsa;
```
https://github.com/auth0/node-jwks-rsa/blob/master/index.d.ts

## @types/express

```typescript
declare function e(): core.Express;

declare namespace e {
  var json: typeof bodyParser.json;
  ...
}

export = e;
```
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/express/index.d.ts

**Comment by leaumar** [comment]
Having read up on the issue again some more with a clearer head, I agree this ticket can't really go anywhere new, @adamjmcgrath . The problem is talked about plenty online, but there seem to be no "clever tricks" or anything aside from making a hybrid library with multiple exposed files to import from (each with a different module system). `esModuleInterop` is simply the way to go with any commonjs being imported into es6. Thanks for your input and patience. :)

**Comment by davidpatrick** [comment]
Thanks @adamjmcgrath and @leaumar for working this one out.
